# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='laglat',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
