# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 04:23
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_laglat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='laglat',
        ),
        migrations.AddField(
            model_name='post',
            name='lnglat',
            field=models.CharField(blank=True, max_length=40, validators=[blog.models.lnglat_validator]),
        ),
    ]
